web:
  image: tukiyo3/php5.6-apache
  volumes:
      - ./src/:/var/www/html
      - ./logs/:/var/log/apache2/
      - ./files/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./files/php.ini:/usr/local/etc/php/php.ini
  ports:
      - "8080:80"
  #restart: always
